'use strict';

const fs = require('fs');
const path = require('path');

const CONFIG_PATH = 'C:\\ProgramData\\KunekAgent\\config.json';

let _config = null;

/**
 * config.json schema:
 * {
 *   stationId: string,            // "PC-01"
 *   firestoreProjectId: string,   // "kunek-prod"
 *   firebaseApiKey: string,
 *   firebaseAuthDomain: string,   // "kunek-prod.firebaseapp.com"
 *   agentEmail: string,           // generated by Admin → Stations → Generate Token
 *   agentPassword: string,        // generated by Admin → Stations → Generate Token
 *   videoBackgroundPath: string,  // "C:\\ProgramData\\KunekAgent\\bg.mp4"
 *   provisionedAt: string,
 * }
 */
function loadConfig() {
  if (!fs.existsSync(CONFIG_PATH)) {
    throw new Error(`Config not found at ${CONFIG_PATH}. Run: node scripts/provision.js`);
  }
  const raw = fs.readFileSync(CONFIG_PATH, 'utf-8');
  _config = JSON.parse(raw);

  const required = ['stationId', 'agentEmail', 'agentPassword', 'firestoreProjectId', 'firebaseApiKey'];
  for (const field of required) {
    if (!_config[field]) throw new Error(`config.json missing required field: ${field}`);
  }
  return _config;
}

function getConfig() {
  if (!_config) return loadConfig();
  return _config;
}

module.exports = { loadConfig, getConfig };
