'use strict';

/**
 * Firebase client SDK init.
 *
 * The agent authenticates with the Firebase *client* SDK (not Admin), using
 * email/password credentials generated by Admin → Stations → Generate Token.
 * After signInWithEmailAndPassword(), the Auth SDK automatically refreshes the
 * ID token before it expires — no manual refresh needed.
 *
 * Firestore Security Rules enforce the agent's limited write scope:
 *   - read own station doc
 *   - write agentLastPing / isOnline / tamperAlert on own station (agentUid match)
 *   - create station_logs documents
 *   - update its own active session (minutesUsed, lastHeartbeatAt)
 */

const { initializeApp } = require('firebase/app');
const { getAuth, signInWithEmailAndPassword } = require('firebase/auth');
const { getFirestore } = require('firebase/firestore');

const { getConfig } = require('./config');
const logger = require('./logger');

let _app  = null;
let _auth = null;
let _db   = null;

async function initFirebase() {
  const config = getConfig();

  _app = initializeApp({
    apiKey:      config.firebaseApiKey,
    authDomain:  config.firebaseAuthDomain,
    projectId:   config.firestoreProjectId,
  });

  _auth = getAuth(_app);
  _db   = getFirestore(_app);

  logger.info('Firebase app initialized — signing in as agent...');
  const credential = await signInWithEmailAndPassword(_auth, config.agentEmail, config.agentPassword);
  logger.info(`Authenticated. UID: ${credential.user.uid}`);

  return { app: _app, auth: _auth, db: _db };
}

function getDB() {
  if (!_db) throw new Error('Firebase not initialized. Call initFirebase() first.');
  return _db;
}

function getAuthInstance() {
  if (!_auth) throw new Error('Firebase not initialized. Call initFirebase() first.');
  return _auth;
}

module.exports = { initFirebase, getDB, getAuthInstance };
